output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = aws_eks_cluster.servicesweb-eks.endpoint
}
output "cluster_id" {
  description = "EKS cluster ID."
  value       = aws_eks_cluster.servicesweb-eks.id
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = aws_security_group.all_worker_mgmt.id
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "wordpress_db_enpoint" {
  value = module.rds.wordpress_db_enpoint
}

output "db_name" {
  value = var.db_instance_name
}

output "db_username" {
  value = var.MYSQL_DB_USER
}

output "db_password" {
  value = var.MYSQL_DB_PWD
}

/*
output "lb_ip" {
  value = aws_eks_cluster.servicesweb-eks.
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = aws_eks_cluster.servicesweb-eks.
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
  //kubernetes_config_map.aws_auth.*
}*/